CREATE DATABASE COMPANY2 ;
USE COMPANY2 ;

CREATE TABLE COMPANY_INFO2 (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
EMP_NAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
CITY VARCHAR(50) NOT NULL,
AGE INT NOT NULL,
DOJ DATE NOT NULL,
DESIGNATION VARCHAR(50) NOT NULL,
SALARY DECIMAL(15,2) NOT NULL,
MOBILE VARCHAR(10) NOT NULL);

select * from COMPANY_INFO2 ;

select id,emp_name
from company_info2
where designation='trainer' and city='akola'
